# PHP8.0 & ES7.14.0 CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        environment:
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - cluster.name: es-cluster
          - discovery.type: single-node
          - xpack.security.enabled: false
          - ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    steps:
      - checkout

      - run: sudo apt update

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      # Wait for ES startup
      - run:
          name: Waiting for Elasticsearch
          command: dockerize --wait http://localhost:9200 -timeout 1m
      # run tests with phpunit
      - run: composer test
